spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:32768/sfg_prod
    username: sfg_prod_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
